<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>

<?= $this->render($variables, 'modules/catalog/specialist_filter'); ?>

<section class="specialists">
	<div class="container">
		<div class="js--items-scope">
			<?php // Specialists ?>
			<div class="lazy-html lazy-html--init" data-path="catalog/specialists" data-params="<?= $this->htmlParams(['page_id' => $variables['page']['id'], 'header' => $variables['page']['header']]) ?>"></div>
		</div>
	</div>
</section>