<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>
<?php {
	$variables = $this->parseData($variables);
	// echo $this->dump($variables);

	$items = isset($variables['lines']) ? $variables['lines'] : $variables['items'];
	if(!(is_array($items) && count($items))){
		return;
	}
}?>

<?php foreach($items as $item): ?>
	<div class="prices-detail">
		<div class="prices-detail-title"><?= $item['text'] ?>
			<?php if(isset($item['price']) && $item['price'] > 0): ?>
				<span>&nbsp;—&nbsp;<b><?= $item['price'] ?></b>&nbsp;руб.</span>
			<?php endif; ?>
		</div>
		<?php if(isset($item['properties']) && isset($item['properties']['descr']) && !empty($item['properties']['descr'])): ?>
			<?php {
				$descr = preg_replace('/[Ё]/u', 'Е', $item['properties']['descr']);
			} ?>
			<div class="prices-detail-descr"><?= $this->parseWysiwig($descr, $this) ?></div>
		<?php endif; ?>
	</div>
<?php endforeach; ?>




