<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>

<div class="col-xl-3 col-lg-4 col-6">
	<a href="<?= $variables['link'] ?>" class="specialists-item">
		<?php if(isset($variables['properties']['photo'])): ?>
			<?= $this->render([
				'class' => 'responsive',
				'src' => $variables['properties']['photo']['src'],
				'alt' => $variables['properties']['h1'],
				'width' => 260,
				'height' => 370,
			], 'utils/thumb'); ?>
		<?php else: ?>
			<?= $this->render([
				'class' => 'responsive opacity-05',
				'src' => './resources/images/specialist-empty.jpg',
				'alt' => $variables['properties']['h1'],
				'width' => 260,
				'height' => 370,
			], 'utils/thumb'); ?>
		<?php endif; ?>
		<div class="specialists-item-name"><?= $variables['properties']['h1'] ?></div>
		<div class="specialists-item-profession">
			<?php {
				$spec = [];
				$specializations = $variables['properties']['specialization'];
				foreach($specializations as $specId){
					$spec[] = umiObjectsCollection::getInstance()->getObject($specId)->getName();
				}

				echo implode(',<br/>', $spec);
			}?>
		</div>
	</a>
</div>