<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>
<?php {
	list($h1) = $this->properties($variables['page']['obj'], ['h1']);
} ?>
<section class="news">
	<div class="container">
		<div class="s-title"><?= $h1 ?></div>

		<div class="js--items-scope">
			<?php // Specialists ?>
			<div class="lazy-html lazy-html--init" data-path="news/items" data-params="<?= $this->htmlParams(['page_id' => $variables['page']['id']]) ?>"></div>
		</div>
	</div>
</section>
