<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>

<?php foreach ($variables['form']['void:groups'] as $group): ?>
    <?php if (!isset($variables['isHeaderShow']) || (isset($variables['isHeaderShow']) && $variables['isHeaderShow']) ): ?>
        <h4>
            <?php echo $group['attribute:title']?>
        </h4>
    <?php endif; ?>

    <?php foreach ($group['void:fields'] as $field): ?>
        <div>
            <label title="<?php echo isset($field['attribute:tip']) ? $field['attribute:tip'] : ''?>" <?php echo isset($field['attribute:required']) ? 'class="required"' : ''?>>
                <span><?php echo $field['attribute:title']?>:</span>

                <?php echo $this->render(array('field' => $field), 'modules/data/formField/' . $field['attribute:type'])?>

            </label>
        </div>
    <?php endforeach; ?>

<?php endforeach; ?>
