<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>

<?php {
	$settings = $variables['SITE_SETTINGS'];

	// Кнопки расписания и актуальной информации в самом верху
	$hdrBtnSchedule = $settings->getValue('hdr_btn_schedule');
	if(is_array($hdrBtnSchedule) && count($hdrBtnSchedule) && ($hdrBtnSchedule[0] instanceof umiHierarchyElement) &&
		$hdrBtnScheduleId = $hdrBtnSchedule[0]->getId()){
		$hdrBtnSchedulePath = umiHierarchy::getInstance()->getPathById($hdrBtnScheduleId, false);
	}

	$hdrBtnInfo = $settings->getValue('hdr_btn_info');
	if(is_array($hdrBtnInfo) && count($hdrBtnInfo) && ($hdrBtnInfo[0] instanceof umiHierarchyElement) &&
		$hdrBtnInfoId = $hdrBtnInfo[0]->getId()){
		$hdrBtnInfoPath = umiHierarchy::getInstance()->getPathById($hdrBtnInfoId, false);
	}

	$hdrAdditionalClass = '';
	if(isset($hdrBtnSchedulePath) && !isset($hdrBtnInfoPath)){
		$hdrAdditionalClass = 'no-info';
	}
	if(!isset($hdrBtnSchedulePath) && isset($hdrBtnInfoPath)){
		$hdrAdditionalClass = 'no-schedule';
	}



	// Логотип
	$logoPic = $settings->getValue('logo_pic');
	$logoPicX2 = $settings->getValue('logo_pic_x2');

//	$logoName = $settings->getValue('logo_name');
//	$copyright = $settings->getValue('copyright');
//	$companyName = $settings->getValue('company_name');



	// Телефонные номера
	$phoneNumbers = $settings->getValue('phone_numbers');
	$phones = [];
	if(!empty($phoneNumbers)){
		$phones = explode(',', $phoneNumbers);
	}

	// Ссылка на контакты
	$contactsLink = $settings->getValue('contacts_link');


	// Ссылка на внешний личный кабинет
	$hdrBtnCabinet = $settings->getValue('hdr_btn_cabinet');
} ?>


<header>
	<div class="header-top <?= $hdrAdditionalClass ?>">
		<div class="container">
			<div class="row">
				<?php if(isset($hdrBtnSchedulePath) && isset($hdrBtnInfoPath)): ?>
					<div class="col-lg-6">
						<a href="<?= $hdrBtnSchedulePath ?>" class="header-top-item">
							<img src="/resources/images/schedule-icon.svg" alt="ico">
							<span>
								График работы
							</span>
						</a>
					</div>
					<div class="col-lg-6">
						<a href="<?= $hdrBtnInfoPath ?>" class="header-top-item">
							<img src="/resources/images/acutal-info-icon.svg" alt="ico">
							<span>
								Актуальная информация
							</span>
						</a>
					</div>
				<?php elseif(isset($hdrBtnSchedulePath) && !isset($hdrBtnInfoPath)): ?>
					<div class="col-lg-12">
						<a href="<?= $hdrBtnSchedulePath ?>" class="header-top-item">
							<img src="/resources/images/schedule-icon.svg" alt="ico">
							<span>
								График работы
							</span>
						</a>
					</div>
				<?php elseif(!isset($hdrBtnSchedulePath) && isset($hdrBtnInfoPath)): ?>
					<div class="col-lg-12">
						<a href="<?= $hdrBtnInfoPath ?>" class="header-top-item">
							<img src="/resources/images/acutal-info-icon.svg" alt="ico">
							<span>
								Актуальная информация
							</span>
						</a>
					</div>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<div class="header-main">
		<div class="container">
			<?php if(isset($phones[0])): ?>
				<a href="tel:<?= preg_replace('/\(|\)|\-|\s/', '', $phones[0]) ?>" class="header-phone">
					<img src="/resources/images/phone-ico.svg" alt="ico">
					<span><?= $phones[0] ?></span>
				</a>
			<?php endif; ?>
			<a href="#" onclick="event.preventDefault(); window.location.href='<?= $contactsLink ?>'; return false;" class="header-contacts-link">Контакты</a>
			<?php if($variables['request-uri'] !== ($variables['host']. '/') || !empty($_GET['_err'])): ?>
				<a href="/" class="header-logo">
					<img src="<?= $logoPic ?>" srcset="<?= $logoPicX2 ?> 2x" alt="logo">
				</a>
			<?php else: ?>
				<span class="header-logo">
					<img src="<?= $logoPic ?>" srcset="<?= $logoPicX2 ?> 2x" alt="logo">
				</span>
			<?php endif; ?>

			<div class="header-social">
				<?= $this->render($variables, 'main/block_social'); ?>
			</div>


			<?php if(!empty($hdrBtnCabinet)): ?>
				<a href="#" class="header-cabinet" onclick="event.preventDefault(); window.open('<?= $hdrBtnCabinet ?>', '_blank');" >
					<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path d="M11.625 5.625L14.25 3M15.75 1.5L14.25 3L15.75 1.5ZM8.54246 8.7075C8.92972 9.0896 9.23756 9.54453 9.44828 10.0461C9.65899 10.5477 9.76841 11.0859 9.77023 11.63C9.77205 12.174 9.66625 12.713 9.4589 13.216C9.25155 13.7189 8.94676 14.1759 8.56207 14.5606C8.17738 14.9453 7.7204 15.2501 7.21744 15.4574C6.71447 15.6648 6.17546 15.7706 5.63144 15.7688C5.08741 15.7669 4.54912 15.6575 4.04755 15.4468C3.54599 15.2361 3.09106 14.9283 2.70896 14.541C1.95756 13.763 1.54178 12.721 1.55118 11.6395C1.56058 10.5579 1.9944 9.52331 2.75921 8.7585C3.52402 7.99369 4.55862 7.55987 5.64018 7.55047C6.72174 7.54107 7.76373 7.95685 8.54171 8.70825L8.54246 8.7075ZM8.54246 8.7075L11.625 5.625L8.54246 8.7075ZM11.625 5.625L13.875 7.875L16.5 5.25L14.25 3L11.625 5.625Z"  stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
					</svg>
					<span>
						Портал
					</span>
				</a>
			<?php endif; ?>

			<div class="hamburger hamburger--spin">
				<div class="hamburger-box">
					<div class="hamburger-inner"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="header-search">
		<div class="container">
			<?= $this->render([], 'modules/search/form'); ?>
		</div>
	</div>

	<nav>
		<div class="container">
			<?= $this->render($variables, 'modules/menu/header'); ?>
		</div>
	</nav>
</header>