<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>
<?php
{
    $scope = $this->getScopeVars();
    $page_id = intval($scope['page']['id']);
    $page_header = $scope['page']['name'];
    $variables = $this->parseData($variables);
}
?>
<?php if ( isset( $variables[ "items" ] ) && count( $variables[ "items" ] ) ): ?>
	<div class="breadcrumbs">
    	<div class="container">
			<div class="breadcrumbs-list">
				<ul class="breadcrumbs-items">
					<li class="breadcrumbs-item">
						<a class="breadcrumbs-link" href="/">Главная</a>
					</li>
					<?php foreach ($variables['items'] as $item ): ?>
						<li class="breadcrumbs-item">
							<?php if ($item['id'] === intval($page_id)): ?>
								<span class="breadcrumbs-link"><?php echo $page_header ?></span>
							<?php else: ?>
								<a class="breadcrumbs-link" href="<?php echo $this->macros('custom', 'getCanonicalLink', [$item['id']]); ?>"><?php echo $item[ "text" ]; ?></a>
							<?php endif; ?>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
    </div>
<?php endif; ?>