<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>
<?php $variables = $this->parseData( $variables ); ?>
<?php
$rate_voters = $variables[ "rate" ][ "voters" ];
$rate_sum = $variables[ "rate" ][ "sum" ];
$rate_value = $variables[ "rate" ][ "value" ];
$rate_floor = floor( $rate_value );
?>
<div id="js--rating-<?php echo $variables["id"]; ?>" class="rating" itemscope="itemscope" itemtype="http://schema.org/AggregateRating">
    <meta itemprop="itemReviewed" content="<?php echo $variables[ "name" ]; ?>">
    <meta itemprop="ratingValue" content="<?php echo $rate_value; ?>">
    <meta itemprop="ratingCount" content="<?php echo $rate_voters; ?>">
    <meta itemprop="bestRating" content="<?php echo $rate_value; ?>">
    <ul class="rating__items">
        <?php for ( $i = 5; $i > 0; $i-- ): ?>
            <li class="rating__item">
                <a class="rating__link js--onclick-rate-page" data-rate="<?php echo $i; ?>" data-page-id="<?php echo $variables[ "id" ]; ?>" title="<?php echo $i; ?>"><span class="spr spr--jug-<?php echo ( $rate_floor >= $i ? "full" : "empty" );?>"></a>
            </li>
        <?php endfor; ?>
    </ul>
    <small id="js--rating-status-<?php echo $variables["id"]; ?>" class="rating__status color-gray">
        <?php if ( $rate_voters > 0 ): ?><?php echo $rate_voters . " " . $this->translate( "l-rate-voters" ) ; ?><?php endif; ?>
    </small>
</div>