<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>
<div class="row row--align row--margin-none">
    <span class="cell cell--middle cell--padding-none">
        <?php echo $this->render( array(
            "type" => "link",
            "link" => "//vk.com/club143289413",
            "target" => "_blank",
            "class" => array( "wrapper" ),
            "sprite" => array( "before", "spr spr--soc-vk" )
        ), "utils/button" ); ?>
    </span>
    <span class="cell cell--middle cell--padding-none cell--padding-left">
        <?php echo $this->render( array(
            "type" => "link",
            "link" => "//www.instagram.com/lavkabahusa/",
            "target" => "_blank",
            "class" => array( "wrapper" ),
            "sprite" => array( "before", "spr spr--soc-is" )
        ), "utils/button" ); ?>
    </span>
</div>