<div class="fixed-btns">
	<div class="fixed-btns-item request popup-btn" popup-id="popup-request">
		<img src="/resources/images/request.svg" alt="ico">
			<span>
				Запись на прием
			</span>
	</div>
	<div class="fixed-btns-item quest-answer popup-btn" popup-id="popup-quest-answer">
		<img src="/resources/images/quest-answer.svg" alt="ico">
			<span>
				Вопрос-ответ
			</span>
	</div>
</div>

<div class="popup" id="popup-request">
	<div class="popup-inner">
		<div class="popup-close">
			<img src="/resources/images/popup-close.svg" alt="ico">
		</div>
		<div class="popup-top">
			<img src="/resources/images/request.svg" alt="ico">
			<div class="popup-title">
				Запись на прием
			</div>
		</div>
		<div class="popup-main">
			<div class="popup-info">
				<div class="popup-info-title">
					Форма предназначена только для записи на прием!
				</div>
				<p>
					Письма с вопросами, отправленные с помощью формы «Записи на прием», обрабатываются автоматически и не позволяют отвечать на вопросы! <br><br>
					Пожалуйста, прочтите <a href="#">правила пользования формой «Запись на прием»</a>.
				</p>
			</div>
			<form action="#" class="popup-form">
				<input type="text" placeholder="Ваше имя">
				<input type="text" placeholder="Номер телефона">
				<input type="text" placeholder="E-mail для ответа">
				<input type="text" placeholder="Сообщение">
				<button>
					Записаться на прием
				</button>
			</form>
			<div class="popup-form-agreement">
				Отправляя данные через форму, вы подтверждаете, что согласны на обработку персональных данных и принимаете <a href="#">Политику конфиденциальности</a>.
			</div>
		</div>
	</div>
</div>

<div class="popup" id="popup-quest-answer">
	<div class="popup-inner">
		<div class="popup-close">
			<img src="/resources/images/popup-close.svg" alt="ico">
		</div>
		<div class="popup-top">
			<img src="/resources/images/quest-answer.svg" alt="ico">
			<div class="popup-title">
				Вопрос-ответ
			</div>
		</div>
		<div class="popup-main">
			<div class="popup-info">
				<div class="popup-info-title">
					Форма предназначена только для обратной связи!
				</div>
				<p>
					Письма с записью на прием, отправленные с помощью формы «Вопрос-Ответ» не могут быть обработаны! <br><br>
					Пожалуйста, прочтите <a href="#">правила пользования формой «Вопрос-Ответ»</a>.
				</p>
			</div>
			<form action="#" class="popup-form">
				<input type="text" placeholder="Ваше имя">
				<input type="text" placeholder="Номер телефона">
				<input type="text" placeholder="E-mail для ответа">
				<input type="text" placeholder="Сообщение">
				<button>
					Отправить
				</button>
			</form>
			<div class="popup-form-agreement">
				Отправляя данные через форму, вы подтверждаете, что согласны на обработку персональных данных и принимаете <a href="#">Политику конфиденциальности</a>.
			</div>
		</div>
	</div>
</div>