<style type="text/css">
    body {
        font-family: "Arial", Sans-Serif;
    }
    .center {
        padding-top: 50px;
        margin-left: auto;
        margin-right: auto;
        width: 980px;
        text-align: center;
    }
    .exception-heading {
        margin-top: 0;
        margin-bottom: 20px;
        font-family: inherit;
        font-weight: 700;
    }
    .exception-message {
        font-size: 18px;
    }
</style>
<div class="center">
    <h3 class="exception-heading">Ошибка!</h3>
    <div class="exception-message">%s</div>
    <div class="back-home">
        <a href="/">Вернуться на главную</a>
    </div>
</div>