<?php /** @var CwrkExtensions $this */ ?>
<?php /** @var array $variables */ ?>

<section class="clinics">
	<div class="container">
		<?php {
			$clinics = $this->macros('content', 'menu', [null, 1, $variables['page']['id']], ['h1', 'phones', 'address', 'schedule', 'header_pic']);
			$clinics = $this->parseData($clinics);
			$clinics = isset($clinics['items']) ? $clinics['items'] : [];
		} ?>

		<?php foreach($clinics as $clinic): ?>
			<?php {
				$props = $clinic['properties'];
				// $this->dump($clinic);
			} ?>

			<div class="clinic-card">
				<div class="clinic-card-photo">
					<?php if(isset($props['header_pic'])): ?>
						<?= $this->render([
							'class' => 'responsive',
							'src' => $props['header_pic'],
							'alt' => $clinic['name'],
							'width' => 150,
							'height' => 150
						], 'utils/thumb'); ?>
					<?php else: ?>
						<?= $this->render([
							'class' => 'responsive opacity-05',
							'src' => './resources/images/clinic-empty.jpg',
							'alt' => $clinic['name'],
							'width' => 150,
							'height' => 150
						], 'utils/thumb'); ?>
					<?php endif; ?>
				</div>
				<div class="clinic-card-content">
					<div class="clinic-card-title"><?= $props['h1'] ?></div>
					<a href="<?= $clinic['link'] ?>" class="clinic-card-link">
						<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M9 16.5C13.1421 16.5 16.5 13.1421 16.5 9C16.5 4.85786 13.1421 1.5 9 1.5C4.85786 1.5 1.5 4.85786 1.5 9C1.5 13.1421 4.85786 16.5 9 16.5Z"  stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
							<path d="M9 12V9" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
							<path d="M9 6H9.0075" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
						</svg>
						<span>Информация</span>
					</a>
					<div class="clinic-card-info">
						<div class="clinic-card-phones">
							<?php $phones = explode(',', $props['phones']); ?>
							<?php foreach($phones as $phone): ?>
								<a href="tel:<?= $phone ?>"><?= $this->phoneFormat($phone) ?></a>
							<?php endforeach; ?>
						</div>
						<div class="clinic-card-address"><?= $props['address'] ?></div>
						<div class="clinic-card-working-hours"><?= $this->parseWysiwig($props['schedule'], $this) ?></div>
					</div>
				</div>
			</div>
		<?php endforeach; ?>
	</div>
</section>